### ISSUE TITLE
pr_err is not found in dictionary.

### ISSUE THREAD

**Issue by iamkeyur** [jjhenkel/code-vectors-artifact#3]
Hi,

I tried to find similar words to pr_err. It is not in dictionary. pr_err is abundantly used in kernel.

**Comment by jjhenkel** [comment]
Hi @iamkeyur,

This makes sense: `pr_err` is not a symbol that would be included in our vocabulary. `pr_err` is defined as a macro. Therefore, during kernel build (as part of preprocessing), it is expanded and no longer appears in the source code. Due to this, our analysis (and learned vectors) will never see the `pr_err` symbol.

This is a problem with using a GCC plugin that reads the code in Gimple SSA form. I have no way to do analysis on things like preprocessor defines at that stage of compilation. You could trace it back to whatever the definition is and see if any of those words appear in the vocabulary.

Hope this helps!

Jordan

**Comment by iamkeyur** [comment]
Hi,

Any alternative for avoiding macro expansions. Because, macros are something that I'm interested in for research.

**Comment by jjhenkel** [comment]
Hi @iamkeyur ,

Unfortunately no. Macros must be expanded prior to compilation and the analyzer must compile the project to do the lightweight symbolic execution we described in the paper.

If you are interested in macros perhaps try tokenizing the source and running a word-vector learner on that! That's a much more lightweight approach and may be good enough depending on your downstream goals!

**Comment by iamkeyur** [comment]
Thanks. I'll try that.
